"""Research-automation agents (Phase 1+).

Built on :mod:`llmesh.core` primitives, this package hosts the
domain-specific research orchestration agents (literature, hypothesis,
planner, executor, reviewer). Each agent is backend-agnostic: callers
inject an :data:`ExtractFn` that wraps any concrete LLM backend
(Ollama, Anthropic, ...) or a mock for deterministic testing.
"""

from __future__ import annotations

from llmesh.research.hypothesis import (
    Hypothesis,
    HypothesisAgent,
    HypothesisRequest,
    HypothesisResponse,
    build_hypothesis_prompt,
    mock_hypothesis_extract,
    parse_hypothesis_result,
)
from llmesh.research.literature import (
    ExtractFn,
    LiteratureAgent,
    LiteratureRequest,
    LiteratureResponse,
    build_literature_prompt,
    make_anthropic_extract,
    make_ollama_extract,
    mock_extract,
    parse_literature_result,
)
from llmesh.research.planner import (
    ExperimentPlan,
    ExperimentStep,
    PlannerAgent,
    PlannerRequest,
    PlannerResponse,
    build_planner_prompt,
    mock_planner_extract,
    parse_plan_result,
)
from llmesh.research.robotics import (
    ContactEvent,
    MockMotionPlannerAgent,
    MockPerceptionAgent,
    MockReplanningAgent,
    MockTaskPlannerAgent,
    MotionPlannerAgent,
    PerceptionAgent,
    PerceptionFrame,
    PerceptionRequest,
    PerceptionResponse,
    PlanningRequest,
    PlanningResult,
    Pose6D,
    ReplanRequest,
    ReplanResponse,
    ReplanningAgent,
    RoboticsPipelineResult,
    TaskGoal,
    TaskPlan,
    TaskPlanRequest,
    TaskPlanResponse,
    TaskPlannerAgent,
    Trajectory,
    Waypoint,
    run_robotics_pipeline,
)
from llmesh.research.reviewer import (
    LoopResult,
    ReviewerAgent,
    ReviewerRequest,
    ReviewerResponse,
    Verdict,
    VerdictKind,
    build_reviewer_prompt,
    mock_reviewer_extract,
    parse_verdict_result,
    run_plan_review_loop,
)

__all__ = [
    "ContactEvent",
    "ExperimentPlan",
    "ExperimentStep",
    "ExtractFn",
    "Hypothesis",
    "HypothesisAgent",
    "HypothesisRequest",
    "HypothesisResponse",
    "LiteratureAgent",
    "LiteratureRequest",
    "LiteratureResponse",
    "LoopResult",
    "MockMotionPlannerAgent",
    "MockPerceptionAgent",
    "MockReplanningAgent",
    "MockTaskPlannerAgent",
    "MotionPlannerAgent",
    "PerceptionAgent",
    "PerceptionFrame",
    "PerceptionRequest",
    "PerceptionResponse",
    "PlannerAgent",
    "PlannerRequest",
    "PlannerResponse",
    "PlanningRequest",
    "PlanningResult",
    "Pose6D",
    "ReplanRequest",
    "ReplanResponse",
    "ReplanningAgent",
    "ReviewerAgent",
    "ReviewerRequest",
    "ReviewerResponse",
    "RoboticsPipelineResult",
    "TaskGoal",
    "TaskPlan",
    "TaskPlanRequest",
    "TaskPlanResponse",
    "TaskPlannerAgent",
    "Trajectory",
    "Verdict",
    "VerdictKind",
    "Waypoint",
    "run_robotics_pipeline",
    "build_hypothesis_prompt",
    "build_literature_prompt",
    "build_planner_prompt",
    "build_reviewer_prompt",
    "make_anthropic_extract",
    "make_ollama_extract",
    "mock_extract",
    "mock_hypothesis_extract",
    "mock_planner_extract",
    "mock_reviewer_extract",
    "parse_hypothesis_result",
    "parse_literature_result",
    "parse_plan_result",
    "parse_verdict_result",
    "run_plan_review_loop",
]
