"""Research-automation agents (Phase 1+).

Built on :mod:`llmesh.core` primitives, this package hosts the
domain-specific research orchestration agents (literature, hypothesis,
planner, executor, reviewer). Each agent is backend-agnostic: callers
inject an :data:`ExtractFn` that wraps any concrete LLM backend
(Ollama, Anthropic, ...) or a mock for deterministic testing.
"""

from __future__ import annotations

from llmesh.research.composition import (
    ComponentScore,
    CompositionPlan,
    ValueFn,
    compose,
)
from llmesh.research.e2e import E2EResult, run_research_pipeline
from llmesh.research.fidelity import (
    DEFAULT_TIER_ORDER,
    FidelityResult,
    FidelityRunner,
    FidelityTier,
    PipelineConfig,
    PipelineRun,
    make_mock_runner,
    run_pipeline,
)
from llmesh.research.experiment_selector import (
    Belief,
    BeliefStore,
    CandidateExperiment,
    RankedCandidate,
    SelectionReport,
    expected_information_gain,
    rank_candidates,
    select_next,
)
from llmesh.research.failure_driven import (
    DEFAULT_STRATEGIES,
    FailedExperiment,
    FailureDrivenGenerator,
    FailureDrivenRequest,
    InversionStrategy,
    invert_failures,
    mock_failure_driven_extract,
)
from llmesh.research.paper_exporter import (
    ExportBundle,
    export_metrics_csv,
    export_paper_bundle,
    export_runs_csv,
    iter_trace,
    render_paper_md,
    render_timing_svg,
)
from llmesh.research.executor import (
    ExperimentExecutor,
    ExperimentResult,
    MockExperimentExecutor,
    StepRun,
    summarise_result,
)
from llmesh.research.hypothesis import (
    Hypothesis,
    HypothesisAgent,
    HypothesisRequest,
    HypothesisResponse,
    build_hypothesis_prompt,
    mock_hypothesis_extract,
    parse_hypothesis_result,
)
from llmesh.research.literature import (
    ExtractFn,
    LiteratureAgent,
    LiteratureRequest,
    LiteratureResponse,
    build_literature_prompt,
    make_anthropic_extract,
    make_ollama_extract,
    mock_extract,
    parse_literature_result,
)
from llmesh.research.planner import (
    ExperimentPlan,
    ExperimentStep,
    PlannerAgent,
    PlannerRequest,
    PlannerResponse,
    build_planner_prompt,
    mock_planner_extract,
    parse_plan_result,
)
from llmesh.research.ros2_demo import (
    ROS2_MOTION_TOOL_NAME,
    MockROS2MotionTool,
    ROS2DemoResult,
    ROS2MotionRequest,
    ROS2MotionResponse,
    ROS2Unavailable,
    make_ros2_motion_tool,
    run_ros2_demo_loop,
)
from llmesh.research.robotics import (
    ContactEvent,
    MockMotionPlannerAgent,
    MockPerceptionAgent,
    MockReplanningAgent,
    MockTaskPlannerAgent,
    MotionPlannerAgent,
    PerceptionAgent,
    PerceptionFrame,
    PerceptionRequest,
    PerceptionResponse,
    PlanningRequest,
    PlanningResult,
    Pose6D,
    ReplanRequest,
    ReplanResponse,
    ReplanningAgent,
    RoboticsPipelineResult,
    TaskGoal,
    TaskPlan,
    TaskPlanRequest,
    TaskPlanResponse,
    TaskPlannerAgent,
    Trajectory,
    Waypoint,
    run_robotics_pipeline,
)
from llmesh.research.reviewer import (
    LoopResult,
    ReviewerAgent,
    ReviewerRequest,
    ReviewerResponse,
    Verdict,
    VerdictKind,
    build_reviewer_prompt,
    mock_reviewer_extract,
    parse_verdict_result,
    run_plan_review_loop,
)

__all__ = [
    "Belief",
    "BeliefStore",
    "CandidateExperiment",
    "ComponentScore",
    "CompositionPlan",
    "ContactEvent",
    "DEFAULT_STRATEGIES",
    "E2EResult",
    "ExperimentExecutor",
    "ExperimentPlan",
    "ExperimentResult",
    "ExperimentStep",
    "ExportBundle",
    "ExtractFn",
    "FailedExperiment",
    "FailureDrivenGenerator",
    "FailureDrivenRequest",
    "Hypothesis",
    "HypothesisAgent",
    "HypothesisRequest",
    "HypothesisResponse",
    "InversionStrategy",
    "LiteratureAgent",
    "LiteratureRequest",
    "LiteratureResponse",
    "LoopResult",
    "MockExperimentExecutor",
    "MockMotionPlannerAgent",
    "MockPerceptionAgent",
    "MockROS2MotionTool",
    "MockReplanningAgent",
    "MockTaskPlannerAgent",
    "ROS2_MOTION_TOOL_NAME",
    "ROS2DemoResult",
    "ROS2MotionRequest",
    "ROS2MotionResponse",
    "ROS2Unavailable",
    "MotionPlannerAgent",
    "PerceptionAgent",
    "PerceptionFrame",
    "PerceptionRequest",
    "PerceptionResponse",
    "PlannerAgent",
    "PlannerRequest",
    "PlannerResponse",
    "RankedCandidate",
    "SelectionReport",
    "PlanningRequest",
    "PlanningResult",
    "Pose6D",
    "ReplanRequest",
    "ReplanResponse",
    "ReplanningAgent",
    "ReviewerAgent",
    "ReviewerRequest",
    "ReviewerResponse",
    "RoboticsPipelineResult",
    "StepRun",
    "TaskGoal",
    "TaskPlan",
    "TaskPlanRequest",
    "TaskPlanResponse",
    "TaskPlannerAgent",
    "ValueFn",
    "Trajectory",
    "Verdict",
    "VerdictKind",
    "Waypoint",
    "run_robotics_pipeline",
    "build_hypothesis_prompt",
    "build_literature_prompt",
    "build_planner_prompt",
    "build_reviewer_prompt",
    "compose",
    "expected_information_gain",
    "export_metrics_csv",
    "export_paper_bundle",
    "export_runs_csv",
    "iter_trace",
    "make_ros2_motion_tool",
    "run_ros2_demo_loop",
    "invert_failures",
    "make_anthropic_extract",
    "make_ollama_extract",
    "mock_extract",
    "mock_failure_driven_extract",
    "mock_hypothesis_extract",
    "mock_planner_extract",
    "mock_reviewer_extract",
    "parse_hypothesis_result",
    "parse_literature_result",
    "parse_plan_result",
    "parse_verdict_result",
    "rank_candidates",
    "render_paper_md",
    "render_timing_svg",
    "run_plan_review_loop",
    "select_next",
    "run_research_pipeline",
    "summarise_result",
]
